### ISSUE TITLE
-c leads to "Unknown option" message

### ISSUE THREAD

**Issue by bachev** [aweimann/traitar#51]
Hi,

I'm not sure "-c" for using multiple processors is working as expected. There are two "Unknown option" messages appearing:

bach@serendipity:~/traitar/test$ **traitar phenotype indir samples.txt from_genes outdir -c 12**
running_ annotation with hmmer. This step can take a while. A rough estimate for sequential Pfam annotation of genome samples of ~3 Mbs is 10 min per genome.
Unknown option: will-cite
Unknown option: will-cite

Best,
  B.

PS: (this was on the "traitar-master" ZIP downloaded from github)

**Comment by aweimann** [comment]
Hi,

thank you for your feedback on Traitar. I use the ---will-cite option to silence a message from GNU parallel, which reminds people to cite the GNU parallel paper. This option is not available in every version of parallel, which is why you observe the warning message. In any case the -c option should work as expected. 

Let me know, if Traitar worked for you. Any feedback is greatly appreciated.

Thanks again,

Aaron
